apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mongo
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: "5.0" # Specify the version or tag you want
      annotations:
        description: "MongoDB 5.0 from Docker Hub"
      from:
        kind: DockerImage
        name: docker.io/library/mongo:5.0
      importPolicy:
        insecure: false
      referencePolicy:
        type: Source

