apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: gpo-ns-app
spec:
  params:
    - name: app-name
      description: "Name of the application to deploy"
      default: "parksmap"
  workspaces: []
  tasks:
    - name: openshift-client
      taskRef:
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            # Login to OpenShift if needed (ensure the correct credentials are set)
            echo "Deploying application ${app-name}"
            oc project gpo-ns-app && oc new-app --image=quay.io/openshiftroadshow/parksmap:latest --name=parksmap -l app=rws-demo,component=parksmap,role=frontend

            # Expose the service
            echo "Exposing service parksmap
            oc expose svc/parksmap --port=8080
        - name: VERSION
          value: latest
  finally: []

